//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `StreamApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package app;

/** @hidden */
public class _StreamApplicationPrxI extends com.zeroc.Ice._ObjectPrxI implements StreamApplicationPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
