//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `StreamingApp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spoticeri.Demo;

/** @hidden */
public class _StreamingAppPrxI extends com.zeroc.Ice._ObjectPrxI implements StreamingAppPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
